name: "flask-orari-lavoro"
description: "flask-orari-lavoro"
version: "1.0.0"
slug: "flask-orari-lavoro"
init: false
ingress: true
ingress_entry: "orari"
ingress_port: 8139
ingress_stream: true
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: before
ports:
  8139/tcp: 8139
map:
  - share:rw